### ISSUE TITLE
Ignore the filter if it was not found

### ISSUE THREAD

**Issue by ArtemNehoda** [mohammad-fouladgar/eloquent-builder#81] opened 2020-09-16 12:36 UTC
Hi, I would like to add a dynamic filter (I append the query parameter 'filters[profile_id]' to all urls if user presses on a button
). To do this, the NotFoundFilterException must not be throwed if the Model don't have ProfileIdFilter. Is it possible to ignore the filter if it is absent, and not generate the error? Is there any parameter in the configuration for this?

**Comment by mohammad-fouladgar** [comment] 2020-09-16 13:27
Hi @ArtemNehoda,  Please read this issue #23. I think it can solve your issue. 
But if the issue isn't solved, feel free to any questions and send me a sample code and URL, please.

**Comment by mohammad-fouladgar** [comment] 2020-09-20 12:59
I will close this issue. But feel free to reopen this issue if you need it.

**Closed by mohammad-fouladgar** 2020-09-20 12:59 UTC
